### ISSUE TITLE
Blazor Example - HttpPortalController errors

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#1373]
**Describe the bug**
As per comments on #1372 I have amended the blazor sample to use Csla's base type for ClaimsPrincipal

```
      Csla.Security.CslaClaimsPrincipal cslaPrincipal = new Csla.Security.CslaClaimsPrincipal(claimsPrincipal);
      Csla.ApplicationContext.User = cslaPrincipal;

``` 

This fixes the MobileFormatter complaint that you currently get if you run the sample in master.

However after doing this I now see the following exception when a request is made to the server side dataportal:

> Executed endpoint 'BlazorExample.Server.Controllers.DataPortalController.PostAsync (BlazorExample.Server)'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Flush()
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionBody.Flush()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Csla.Server.Hosts.HttpPortalController.InvokeTextPortal(String operation, Stream requestStream, Stream responseStream)
   at Csla.Server.Hosts.HttpPortalController.PostAsync(String operation)
   at BlazorExample.Server.Controllers.DataPortalController.PostAsync(String operation) in C:\Users\DarrellTunnell\source\repos\csla\Samples\BlazorExample\BlazorExample\Server\Controllers\DataPortalController.cs:line 23
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

A quick google lead me to this: https://github.com/aspnet/AspNetCore/issues/7644

However before I attempt to fix this, it would be good to know I am not the only person seeing this? Does this sample run on anyone elses environments?

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Code that Fails**
Any DP operation sent from the blazor wasm client.

**Stack Trace or Exception Detail**
As above 

**Additional context**

**Comment by dazinator** [comment]
I should mention I am running the program under kestrel server (not iis).

When running under kestrel, adding the following code to startup.cs on the server, prevents this exception. Since asp.net core 3 - the default setting for `AllowSynchronousIO` is now false. As per: https://github.com/aspnet/AspNetCore/issues/7644 it seems this is a breaking change on microsoft's part, but it raises a question - does CSLA code need to change to accomodate it, or are we happy with the solution below - i.e revert the setting.

```
 public void ConfigureServices(IServiceCollection services)
    {
      // If using Kestrel:
      services.Configure<KestrelServerOptions>(options =>
      {
        options.AllowSynchronousIO = true;
      });
```
There is an equivalent for IIS.

**Comment by dazinator** [comment]
PR submitted.

**Comment by dazinator** [comment]
Ahh ok. So it looks like you have fixed the SynchronousIO issue already. The problem is the Blazor server project is using an older `Csla.AspNetCore` package reference. I will fix this by updating that package to the latest, and removing my workaround.

**Comment by rockfordlhotka** [comment]
CSLA should change, yes. It means reworking MobileFormatter and its underlying reader/writer to be async - something I haven't looked into yet.
