### ISSUE TITLE
DataPortalException launching ProjectTracker on iOS

### ISSUE THREAD

**Issue by brinawebb** [MarimerLLC/csla#1630]
**Describe the bug**
Hello. I've found this bug on our app and found that the ProjectTracker app crashes also. Launch the iOS App from the ProjectTracker sample "as is" and received the below error, please find attached also the screenshot. Also, I get the same results switching from the default ptrackerserver.azurewebsites.net/… to a local server.

![ptrackerios](https://user-images.githubusercontent.com/4342718/82125463-ea2eae00-975a-11ea-9714-ff6151085808.png)

**Version and Platform**
CSLA version: 5.1.0
OS:  iOS
Platform: Xamarin

**Code that Fails**
Csla.DataPortalException Message=Unable to read beyond the end of the stream.

**Stack Trace or Exception Detail**
```
  at Csla.DataPortalClient.HttpProxy.Fetch (System.Type objectType, System.Object criteria, Csla.Server.DataPortalContext context, System.Boolean isSync) [0x00193] in <d81675a4e83a43b68b4d8f609a0e1f14>:0 
  at Csla.DataPortal`1[T].DoFetchAsync (System.Type objectType, System.Object criteria, System.Boolean isSync) [0x0023c] in <d81675a4e83a43b68b4d8f609a0e1f14>:0 
  at Csla.DataPortal`1[T].FetchAsync (System.Object[] criteria) [0x00078] in <d81675a4e83a43b68b4d8f609a0e1f14>:0 
  at Csla.DataPortal.FetchAsync[T] () [0x00064] in <d81675a4e83a43b68b4d8f609a0e1f14>:0 
  at ProjectTracker.Library.RoleList.CacheListAsync () [0x00026] in C:\Users\a001\Documents\Source\Sample\ProjectTracker\ProjectTracker.BusinessLibrary.Netstandard\RoleList.cs:55 
  at ProjectTracker.Ui.Xamarin.App.OnStart () [0x0008e] in C:\Users\a001\Documents\Source\Sample\ProjectTracker\ProjectTracker.Ui.Xamarin\ProjectTracker.Ui.Xamarin\App.xaml.cs:34 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.8.3.0/src/Xamarin.iOS/Foundation/NSAction.cs:178 
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.8.3.0/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.8.3.0/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at ProjectTracker.Ui.Xamarin.iOS.Application.Main (System.String[] args) [0x00001] in C:\Users\a001\Documents\Source\Sample\ProjectTracker\ProjectTracker.Ui.Xamarin\ProjectTracker.Ui.Xamarin.iOS\Main.cs:17 
```

**Comment by rockfordlhotka** [comment]
Thanks @brinawebb - someone else (?) reported this within the last couple weeks, but I can't find that post.

I am going to need help figuring this out, because my Mac is old enough that Apple won't upgrade it to the latest MacOS, and therefore I can't run the latest xcode, and therefore the current Xamarin bits. I'm budgeting to buy a new Mac, but those suckers are expensive, especially for a box I only use as a Xamarin compiler 😄 

I am wondering what's going over the wire? Can you use Fiddler to see if the response from the data port is valid, or a server error?

**Comment by brinawebb** [comment]
Thanks Rocky. I'm in the same boat WRT Mac. One of my co-workers said he'll respond.

**Comment by animjn** [comment]
Hi!! I was trying to get to the bottom of the same (I think) issue. @rockfordlhotka, the following is the raw data from Fiddler, hope it helps -

RESPONSE
```
HTTP/1.1 200 OK
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Mon, 18 May 2020 13:40:47 GMT
Content-Length: 1136 

���������.Csla.Server.Hosts.HttpChannel.HttpResponse, /c���������
_fieldManager������������������+Csla.Core.FieldManager.FieldDataManager, /c���������    ErrorData���������������_businessObjectType������������sCsla.Server.Hosts.HttpChannel.HttpResponse, Csla, Version=5.1.0.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30�
GlobalContext������������
ObjectData����������������/Csla.Server.Hosts.HttpChannel.HttpErrorInfo, /c���������������������������������������������������tCsla.Server.Hosts.HttpChannel.HttpErrorInfo, Csla, Version=5.1.0.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30��ExceptionTypeName    �����������System.IO.EndOfStreamException��Message
����������,Unable to read beyond the end of the stream.��Source������������System.Private.CoreLib�
StackTrace�������������   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at Csla.Serialization.Mobile.CslaBinaryReader.Read(Stream serializationStream)
   at Csla.Serialization.Mobile.MobileFormatter.Deserialize(Stream serializationStream)
   at Csla.Server.Hosts.HttpPortalController.InvokePortal(String operation, Stream requestStream, Stream responseStream)
```
REQUEST
```
POST http://192.168.86.103:8040/api/dataportal?operation=fetch HTTP/1.1
Host: 192.168.86.103:8040
Content-Type: application/x-www-form-urlencoded
Connection: keep-alive
Connection: keep-alive
Accept: */*
User-Agent: ProjectTracker.Ui.Xamarin/1.0 CFNetwork/1121.2.1 Darwin/19.2.0
Accept-Language: en-us
Content-Length: 932
Accept-Encoding: gzip, deflate

���������1Csla.Server.Hosts.HttpChannel.CriteriaRequest, /c���������
_fieldManager������������������+Csla.Core.FieldManager.FieldDataManager, /c��������������_businessObjectType������������vCsla.Server.Hosts.HttpChannel.CriteriaRequest, Csla, Version=5.1.0.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30�
ClientContext�����������d�������������Csla.Core.ContextDictionary, /c��������������__dataportaltimer��������������2(_����<��.����
ClientCulture������������en-US��ClientUICulture������������en-US��CriteriaData�����������3�������������Csla.Server.EmptyCriteria, /c�������������
GlobalContext    ����������5�������������Csla.Core.ContextDictionary, /c�������������    Principal
����������c������������%Csla.Security.CslaClaimsPrincipal, /c��������������s���������������������������������������TypeName�����������vProjectTracker.Library.RoleList, ProjectTracker.BusinessLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

**Comment by EricNgo1972** [comment]
I had the same issue before. 

I resolved it by turning ON UseTextSerialization in DataPortal.

https://github.com/MarimerLLC/csla/issues/1810
