### ISSUE TITLE
Dal with DbContext cannot resolve the context from DI because of the service scope

### ISSUE THREAD

**Issue by joshhanson314** [MarimerLLC/csla#2006]
**Describe the bug**
It seems the changes introduced by @dazinator for issue #1874 have broken the ProjectTracker sample application when switching it from using the Mock Dal to the EF Dal in the ProjectTracker.AppServerCore.Startup.cs.

**Version and Platform**
CSLA version: 5.4.0
OS: Windows
Platform: ASP.NET Core

**Code that Fails**
Provide the failing code, ideally an isolated repro of the issue you are encountering.

**Stack Trace or Exception Detail**
Csla.DataPortalException: DataPortal.Fetch failed (Cannot resolve 'ProjectTracker.Dal.IDashboardDal' from root provider because it requires scoped service 'ProjectTracker.DalEfCore.PTrackerContext'.)
 ---> Csla.Reflection.CallMethodException: Dashboard.Fetch method call failed
 ---> System.InvalidOperationException: Cannot resolve 'ProjectTracker.Dal.IDashboardDal' from root provider because it requires scoped service 'ProjectTracker.DalEfCore.PTrackerContext'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Csla.Reflection.ServiceProviderMethodCaller.CallMethodTryAsync(Object obj, ServiceProviderMethodInfo method, Object[] parameters)
   at Csla.Reflection.LateBoundObject.CallMethodTryAsyncDI[T](Boolean isSync, Object[] parameters)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Csla.Reflection.ServiceProviderMethodCaller.CallMethodTryAsync(Object obj, ServiceProviderMethodInfo method, Object[] parameters)
   at Csla.Reflection.LateBoundObject.CallMethodTryAsyncDI[T](Boolean isSync, Object[] parameters)
   at Csla.Reflection.LateBoundObject.CallMethodTryAsyncDI[T](Boolean isSync, Object[] parameters)
   at Csla.Server.DataPortalTarget.InvokeOperationAsync[T](Object criteria, Boolean isSync)
   at Csla.Server.DataPortalTarget.FetchAsync(Object criteria, Boolean isSync)
   at Csla.Server.SimpleDataPortal.Fetch(Type objectType, Object criteria, DataPortalContext context, Boolean isSync)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Csla.Reflection.ServiceProviderMethodCaller.CallMethodTryAsync(Object obj, ServiceProviderMethodInfo method, Object[] parameters)
   at Csla.Reflection.LateBoundObject.CallMethodTryAsyncDI[T](Boolean isSync, Object[] parameters)
   at Csla.Reflection.LateBoundObject.CallMethodTryAsyncDI[T](Boolean isSync, Object[] parameters)
   at Csla.Server.DataPortalTarget.InvokeOperationAsync[T](Object criteria, Boolean isSync)
   at Csla.Server.DataPortalTarget.FetchAsync(Object criteria, Boolean isSync)
   at Csla.Server.SimpleDataPortal.Fetch(Type objectType, Object criteria, DataPortalContext context, Boolean isSync)
   at Csla.DataPortal`1.HandleDataPortalException(String operation, DataPortalException ex, Boolean isSync, IDataPortalProxy proxy)
   at Csla.DataPortal`1.HandleFetchDataPortalException(DataPortalException ex, Boolean isSync, IDataPortalProxy proxy)
   at Csla.DataPortal`1.DoFetchAsync(Type objectType, Object criteria, Boolean isSync)
   at Csla.DataPortal`1.FetchAsync(Object[] criteria)
   at Csla.DataPortal.FetchAsync[T]()
   at ProjectTracker.AppServerHost.Controllers.DataPortalController.GetAsync() in **************\csla\Samples\ProjectTracker\ProjectTracker.AppServerCore\Controllers\DataPortalController.cs:line 28

**Comment by dazinator** [comment]
This happens because Microsoft DI validates services being registered as scoped, being resolved from the 'root' service provider and throws an exception.

Is `ProjectTracker.AppServerHost` a remote host? If its a remote host running under aspnet core, then csla should be resolving the scoped IServiceProvider for the request and you shouldn't be seeing this error. The fact that you are makes me believe its a remote host running under legacy asp.net or something else? If that's the case, there has been discussiom about allowing CSLA to create a new scope and disposes of it for each request, but this has not been implemented yet (@rockfordlhotka knows more about that). In the meantime, you can add code at the start of each request to create a scoped IServiceProvider and set it in csla application context. If this does sound like the issue then we should also consider updating the sample I guess.

**Comment by joshhanson314** [comment]
I am running the sample application ProjectTracker as is, with the exception of calling services.AddDalEfCore(); instead of services.AddDalMock(); in the Startup.cs in the ProjectTracker.AppServerCore. In order to minimize moving parts, I am just running the ProjectTracker.AppServerCore project in Visual Studio Professional 2019 (configured as a .NET Core 3.1 application) to run the data portal controller Get method that attempts to get the Dashboard object. I am not running the multiple startup projects to get the UI. Core is new to me, but if I am correct in terminology, I am running it as a asp.net core host already.

**Comment by dazinator** [comment]
@joshhanson314 what client code are you running to get the exception? Or does this exception just happen on startup of the host?

**Comment by joshhanson314** [comment]
This just happens on startup.

**Comment by dazinator** [comment]
From the stack trace the error is stemming from a DataPortal.Fetch call. So what is doing a DataPortal.Fetch during startup of the host? Are you sure you don't have a client application doing a fetch after the host has successfully started? Also have you kept this line on the host?

```
services.AddHttpContextAccessor()

```

**Comment by joshhanson314** [comment]
I still have the services.AddHttpContextAccess() line. When I run the project, it opens a browser to http://localhost:8040/api/dataportal and it is attempting to perform the GetAsync() on the DataPortalController.cs to call DataPortal.Fetch for the Library.Dashboard and return the project and resource counts. This is all the sample application, as is, without any modification other than switching the Dal from Mock to Entity Framework. Assuming you have attempted the same, are you not seeing the same exception?

I appreciate your time. I tried several times to pour over your changes for the service provider and see what the breaking change is that Rocky flagged, but I can't see what change is needed.

**Comment by rockfordlhotka** [comment]
I recently ran into a similar issue with a net5.0 app server.

@dazinator are you sure aspnetcore creates a scope automatically? Are we missing some config to make that happen? Or to ensure CSLA gets that scope?

**Comment by dazinator** [comment]
@rockfordlhotka 
Yes I'm sure. The default HttpContext has a .Features property and one of the "features" that is present by default is one that ensures a scope is created as part of every request

See the RequestServicesFeature being set up here: https://github.com/dotnet/aspnetcore/blob/b795ac3546eb3e2f47a01a64feb3020794ca33bb/src/Http/Http/src/DefaultHttpContext.cs

And here is what it does:

https://github.com/dotnet/aspnetcore/blob/b795ac3546eb3e2f47a01a64feb3020794ca33bb/src/Http/Http/src/Features/RequestServicesFeature.cs

Also, note that - if asp.net core did not create a scope per request then none of their own samples would work, as they inject DbContexts into controllers and services in their own samples to load weather data, and no where in that code is it required that a user must add their own code in the request pipeline to create a scope. Aspnet core has always done this from day one.

I haven't tried to replicate this issue yet, but perhaps there is something that is part of the sample apps that is preventing this from happening. I noticed endpoint routing is being disabled in this sample code so perhaps that's it, won't know until I am able to look deeper. Won't be for a while as I'm on Christmas break at the moment.

**Comment by dazinator** [comment]
It might also be worth double checking this is not some issue with IHttpContextAccessor not working correctly due to the fact csla is compiled against one version of asp.net core and their are differences at runtime. @joshhanson314 if you run `dotnet --version` from the command line in the sample project folder, what version of the sdk are you using to run the sample? If the sample is compiled for .net core 2.1 or 3.1, and you are running under 5 then perhaps that is causing an issue. To verify this you could add a global.json file to pin the sdk version to a 2.1 or 3.1 version (whatever the csla project expects)

**Comment by joshhanson314** [comment]
`dotnet --version` yields 5.0.101 for the project. Using the global.json, I was able to use version 3.1.300. It made no change in the error.

@dazinator I'm on Christmas break too (or supposed to be, and yet here I am...) so feel free to let this sit until you get back.

**Comment by dazinator** [comment]
Ok I tracked down the bug.

The code that should detect the asp.net core scoped provider isn't coming into effect, because `ApplicationContext` class is always using the default ContextManager, not the WebContextManager when checking for the current scoped provider:

https://github.com/MarimerLLC/csla/blob/master/Source/Csla/ApplicationContext.cs#L858

I'll submit a PR for a fix for that.

**Comment by dazinator** [comment]
PR submitted.
