### ISSUE TITLE
InvalidOperationException from RegisterProperty

### ISSUE THREAD

**Issue by ajohnstone-ks** [MarimerLLC/csla#2022]
**Describe the bug**
After a app pool recycle, sometimes a race condition is triggered where RegisterProperty calls are happening from a business objects cctor and the properties list has been locked.  A sample stack trace from this [thread](https://github.com/MarimerLLC/csla/discussions/1998):

**Version and Platform**
CSLA version: 5.3.0-3, 5.4.0
OS: Windows
Platform: ASP.NET 

**Code that Fails**
RegisterProperty calls

**Stack Trace or Exception Detail**
```
Csla.DataPortalException: DataPortal.Fetch failed (BusinessObjectInfo.Child_Fetch method call failed) ---> Csla.Reflection.CallMethodException: BusinessObjectList.DataPortal_Fetch method call failed ---> Csla.Reflection.CallMethodException: BusinessObjectInfo.Child_Fetch method call failed ---> System.InvalidOperationException: Cannot register property DeviceType after containing type (BusinessObjectInfo) has been instantiated
at Csla.Core.FieldManager.PropertyInfoManager.RegisterProperty[T](Type objectType, PropertyInfo1 info) at BusinessRules.BusinessObjects.BusinessObjectInfo..cctor() in C:\BuildAgent\work\55c630171023f9ba\businessrules\BusinessObjects\BusinessObjectInfo.cs:line 23 --- End of inner exception stack trace --- at Csla.Reflection.ServiceProviderMethodCaller.<CallMethodTryAsync>d__11.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Csla.Reflection.LateBoundObject.<CallMethodTryAsyncDI>d__121.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Csla.Server.DataPortalTarget.d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Csla.Server.ChildDataPortal.d__9.MoveNext()
--- End of inner exception stack trace ---
at Csla.Reflection.ServiceProviderMethodCaller.d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Csla.Reflection.LateBoundObject.d__121.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Csla.Server.DataPortalTarget.<InvokeOperationAsync>d__141.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Csla.Server.DataPortalTarget.d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Csla.Server.SimpleDataPortal.d__1.MoveNext()
--- End of inner exception stack trace ---
at Csla.DataPortal1.Fetch(Type objectType, Object criteria) at Csla.DataPortal1.Fetch(Object[] criteria)
```

**Additional context**
Suspect a change from this [commit](https://github.com/MarimerLLC/csla/issues/1498) (suggested in the discussion)

**Comment by rockfordlhotka** [comment]
From @coder-rr:

As far as I can tell this is the only thing that changed in this area of code.

#1498 Ensure static fields are initialized once property list is created  (version 5.2.0)

We started to get the error after we updated from version 4.11.2  -> 5.3.1

**Comment by ajohnstone-ks** [comment]
@rockfordlhotka FYI, we are still getting this in the latest version of Csla:

```
Csla.DataPortalException: DataPortal.Fetch failed (WorkOrderReporterInfo.Child_Fetch method call failed) ---> Csla.Reflection.CallMethodException: WorkOrderReporterList.Fetch method call failed ---> Csla.Reflection.CallMethodException: BusinessObjInfo.Child_Fetch method call failed ---> System.InvalidOperationException: Cannot register property DetailOption after containing type (BusinessObjInfo) has been instantiated
   at Csla.Core.FieldManager.PropertyInfoManager.RegisterProperty[T](Type objectType, PropertyInfo`1 info)
   at OurApp.BusinessRules.BizObjs.BusinessObjInfo..cctor() in C:\BuildAgent\work\7345d15f592de9ca\OurApp.businessrules\BizObjs\BusinessObjInfo.cs:line 44
   --- End of inner exception stack trace ---
   at Csla.Reflection.ServiceProviderMethodCaller.<CallMethodTryAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.LateBoundObject.<CallMethodTryAsyncDI>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.DataPortalTarget.<FetchChildAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.ChildDataPortal.<Fetch>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at Csla.Reflection.ServiceProviderMethodCaller.<CallMethodTryAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.LateBoundObject.<CallMethodTryAsyncDI>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.DataPortalTarget.<InvokeOperationAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.DataPortalTarget.<FetchAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.SimpleDataPortal.<Fetch>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   at Csla.DataPortal`1.Fetch(Object[] criteria)
   at OurApp.BusinessRules.BizObjs.BusinessObjList.GetBusinessObjList(IEnumerable`1 facilitiesDepartmentGuids, String cultureID)
   at OurApp.WorkOrderUI.FormBizObjsearch.FillCombosAndLists()
   at OurApp.WorkOrderUI.FormBizObjsearch.FormBizObjsearch_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by rockfordlhotka** [comment]
I need some sort of repro that I can use to test, otherwise I'm shooting in the dark with this.

**Comment by ajohnstone-ks** [comment]
@rockfordlhotka Total understood; we can't reliably reproduce it either; its only in production, and only sometimes after the app pool is recycled.  

Taking a different track for this issue, would it be possible to have a configuration flag that if set, instead of throwing the exception it just silently returns out?  The default for the flag should be off so the exception is thrown, but for us it would prevent the system from going down and having to recover again. 

Would you foresee any other issues with that behavior?

**Comment by rockfordlhotka** [comment]
I don't know. It isn't clear to me how the cache exists already, and yet there's an attempt to load the cache.

Is the cache _really_ loaded? Or partially? Would this config flag open you up to other race conditions we don't even check for, because we assume the cache is valid?

**Comment by ajohnstone-ks** [comment]
@rockfordlhotka All good points I didn't think about.  I'm not sure if the cache already exists because the web app is recycling and there's time were the pools overlap (seems unlikely) or we have enough request that two manage to hit that portion of code at the same time.
