### ISSUE TITLE
DataPortal operation on repeatedly loaded assembly (using AssemblyLoadContext) causing cast exception - Can not cast [A]MyClass from MyAssembly.dll to [B]MyClass from MyAssembly.dll

### ISSUE THREAD

**Issue by BaHXeLiSiHg** [MarimerLLC/csla#2095]
**Describe the bug**
Probably i'm doing something wrong, but will try to explain :\

Have main application with installed CSLA library. On request - loading dynamic assembly using AssemblyLoadContext and calling DataPortal.Fetch method from class within this dynamically loaded assembly.

On first call everything works fine, but after some time of inactivity flushing this not used anymore dynamic assembly, calling AssemblyLoadContext.Unload(), GC.Collect() and GC.WaitForPendingFinalizers().

After period of time trying to access same dynamic assembly via same scenario: loading in AssemblyLoadContext and calling DataPortal.Fetch, but this time getting error:

`
DataPortal.Create failed ([A]MyClass cannot be cast to [B]MyClass. Type A originates from 'MyAssembly.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' in a byte array. Type B originates from 'MyAssembly.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' in a byte array.)
`

That is call stack:

`
   at lambda_method(Closure , Object , Object[] )
   at Csla.Reflection.ServiceProviderMethodCaller.CallMethodTryAsync(Object obj, ServiceProviderMethodInfo method, Object[] parameters)
   at Csla.Reflection.ServiceProviderMethodCaller.CallMethodTryAsync(Object obj, ServiceProviderMethodInfo method, Object[] parameters)
   at Csla.Reflection.LateBoundObject.CallMethodTryAsyncDI[T](Boolean isSync, Object[] parameters)
   at Csla.Server.DataPortalTarget.InvokeOperationAsync[T](Object criteria, Boolean isSync)
   at Csla.Server.DataPortalTarget.FetchAsync(Object criteria, Boolean isSync)
   at Csla.Server.SimpleDataPortal.Fetch(Type objectType, Object criteria, DataPortalContext context, Boolean isSync)
   at Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   at Csla.DataPortal`1.Fetch(Object[] criteria)
   at Csla.DataPortal.Fetch[T](Object[] criteria)
   at MyClass.Fetch(MyFetchCriteria criteria)
`

Any  suggestion what am i doing wrong? As i understand, static fetch method from MyClass was cached somewhere in CSLA and CSLA trying to reuse it.

Could anyone guide me a little?)

**Version and Platform**
CSLA version: 4.7.100
OS: Windows
Platform: ASP.NET Core 3.1

**Comment by BaHXeLiSiHg** [comment]
So there is no way to define some "separate" cache for particular assembly?

What about caching strategy? Is static information are cached via direct type reference or there is some kind of "dictionary" with method/property name to assembly name?

Don't know ho to solve this situation :( Depends on caching, probably i can change version or token of dynamically loaded assembly, every time when it's loaded...

**Comment by BaHXeLiSiHg** [comment]
Well, found this place, that generate key for methods cache:

```csharp
private static string GetCacheKeyName(Type targetType, Type operationType, object[] criteria)
{
      return targetType.FullName + ".[" + operationType.Name.Replace("Attribute", "") + "]" + ServiceProviderMethodCaller.GetCriteriaTypeNames(criteria);
}
```

I can count loadings/unloadings of every dynamic assembly. Is there any way to use this counter in "targetType.FullName"?) Something like "MyClass_1", but i could not understand how to change "FullName" of type within already compiled library oO

**Comment by rockfordlhotka** [comment]
There are a number of things that are cached using static properties, including type info, property info, business rule info. compiled lambda expressions used for invoking constructors, properties, and methods, and probably more.

What you are trying to do has never been in the scope of any design parameter for CSLA, and I suspect it would be a fair amount of work to enable the idea of unloading an assembly.

**Comment by rockfordlhotka** [comment]
@BaHXeLiSiHg I should be clear: I'm open to the idea of a PR that changes all the caching code to accommodate your scenario, assuming (a) it doesn't break people's code; (b) it doesn't have a negative performance impact; (c) it doesn't cause memory leaks or something like that.

**Comment by BaHXeLiSiHg** [comment]
It would be great!

Currently tried to make some Type wrapper in purpose of generating Type.FullName on every DataPortal method execution, to provide different incremented FullNames in case of every reloaded assembly. But it looks weird and i'm facing issues with execution of CSLA methods via reflection...

So, some kind of isolated cache for every instantiated AssemblyLoadContext will do the trick, but it sounds complicated. or any other ideas?

Anyway, i will be glad to help with development in chosen work direction. Also will try to accomplish something with my Type wrapper, probably it will do the trick ^^

**Comment by rockfordlhotka** [comment]
@BaHXeLiSiHg I updated the title and original description of this issue to reflect what we're thinking now, in terms of enhancing CSLA to enable the concept of unloading types from memory. Please read through what I added there and let me know what you think.

**Comment by BaHXeLiSiHg** [comment]
@rockfordlhotka, looks like a task right now)

Not sure, which one way will be better:
1) Trying to link every cached information with current "AppDomain" or loaded "AssemblyLoadContext", using further flushing of information, related with unloaded "AssemblyLoadContext". Will require kind of emitter or overrided "AssemblyLoadContext.Unload()" handler, that will allow to clean cache.
2) Separate cache instances for "AppDomain" and other loaded "AssemblyLoadContext", something like creating new cache on instantiation of "AssemblyLoadContext" and destroying cache after "AssemblyLoadContext.Unload()" was called. Never did something like this before, can imagine that it should be some stack of caches and according to used assembly owner ("AppDomain" or loaded "AssemblyLoadContext") should be used separate cache instance.

**Comment by rockfordlhotka** [comment]
Two things I'm thinking.

First, is that a list of caches is a fair amount of overhead, especially when looking for an item, because we'd have to search all the caches to find the item. Or come up with some top-level unique index for each cache relative to a specific _instance_ of a loaded assembly?

Second, is that we do need to flush or remove the cache(s) when an assembly unloads. Otherwise we'd be creating a memory leak (and who knows what other problems by maintaining "references" to unloaded assembly types.

**Comment by BaHXeLiSiHg** [comment]
If we are going to use separate caches, then list will be unnecessary, dictionary will be enough.

Let me try to explain, library loaded via "AssemblyLoadContext" means to be isolated (at least i hope so), it can reference to any part of application code (inside "AppDomain"), but "AppDomain" does know nothing about this dynamic loaded assembly, so dynamic assembly does not need to access other CSLA caches, except own, created at moment of trying to access cache (invocation of CSLA methods) from any of business classes within this dynamic assembly.

For this purpose will be enough to have a dictionary of type "ConcurrentDictionary<string, WhateverCacheWeNeed>", where key will be something like "FullName" of accessing assembly. When some business class accessing CSLA methods, there are extracted "Type" of accessed class, which has reference to parent assembly, as i saw. Probably cache should be created earlier, at moment of property/rules registration, whatever, by using same scenario. At this point we will have to retrieve cache from dictionary by key, or create a new one in case when dictionary does not have cache for accessed assembly.

What do you thing about this? Any possible problems?

About flushing/removing cache, hmm, as i understood, CSLA caching PropertyInfo, MethodInfo, etc. which instances is part of "System" assembly, so if we are removing records about this information from dictionary (cache) and unloading assembly, garbage collector should be able to clean up after us. But in never dig so deep in "System" assembly and can certainly tell after making/testing this.

**Comment by rockfordlhotka** [comment]
The caches are static fields, and so won't release any references until the process ends. In your example, the process is clearly long-lived, and you are loading/unloading assemblies multiple times during the lifetime of the process.

My concern is that the cache will (a) maintain references to unloaded types (and GC won't get rid of any of that, because the reference from the static remains), (b) when an assembly is _reloaded_ do the newly loaded types replace the existing (invalid) types?

**Comment by BaHXeLiSiHg** [comment]
I see what you mean. Indeed, thare are several issues with memory leaks, connected to "AssemblyLoadContext" functionality. As i noticed, .Net Asp Core team is awere about problem since last year and i hope that they are investigating them :/

For example [https://github.com/dotnet/aspnetcore/issues/21744](url)

In case of assembly relaoding, are we talking about system types, or CSLA "wrappers"? Cause in case of system types, they are not cleaned/replaced after assembly unload, without of responsible caches clearing, as mentioned in issue above. I'm not sure how it would affect CSLA "wrappers", without testing. Probably investigating this behavior will give some hints for .Net Asp Core team to get rid of memory leaks.

**Comment by BaHXeLiSiHg** [comment]
Got another place, where unloadable library (via "AssemblyLoadContext") could not invoke CSLA method, even if method was called inside this unloadable library, which was loaded first time and not reloaded yet.

Invoking "BusinessBase.GetClone()":

```
System.IO.FileNotFoundException: Could not load file or assembly 'MyDynamicLibrary, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. 
File name: 'MyDynamicLibrary, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Csla.Reflection.MethodCaller.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Csla.Reflection.MethodCaller.GetType(String typeName)
   at Csla.Serialization.Mobile.MobileFormatter.GetTypeFromCache(String typeName)
   at Csla.Serialization.Mobile.MobileFormatter.DeserializeAsDTO(List`1 deserialized)
   at Csla.Serialization.Mobile.MobileFormatter.Deserialize(Stream serializationStream)
   at Csla.Core.ObjectCloner.Clone(Object obj)
   at Csla.Core.BusinessBase.GetClone()
```

**Comment by rockfordlhotka** [comment]
OK, that one is interesting, and might provide a clue.

Serializers, including `MobileFormatter`, use a _string_ assembly qualified type name to find the type for deserialization. Not type caching or anything fancy. Literally `Type.GetType(<assembly qualified type name>)`.

The reason I think this might be a valuable clue, is that there's been a "feature" of .NET, literally forever, where the type loader sometimes won't find some types. It is a weird thing, and I don't know the details, other than that back in 2001-2002 I had conversations with some of the .NET leadership about it, and they indicated it is a design decision that, if changed/fixed, would break everything.

The _solution_ is to handle the type loading failure (at an AppDomain/process level), and implement code to help file the type. Normally that's easy, because there actually _is a list of loaded types_ that is valid and current.

It has been years since I did this, so I don't know offhand where to find an example. It is necessary when hosting .NET in Internet Explorer and various other non-traditional hosts. And I think I did it in the old "RunLocal" command back in the CSLA .NET 1.x time period. [So maybe in this view of the repo](https://github.com/MarimerLLC/csla/tree/V1-53)?

**Comment by BaHXeLiSiHg** [comment]
Not sure about that it is kind of bug)

Step before last in stack trace is `System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)` which has `AssemblyLoadContext assemblyLoadContext` as one of arguments.

I think `System.RuntimeTypeHandle.GetTypeByName` didn't receive information about assembly load domain, where type is defined. Most likely the type was looked in `AppDomain` instead of loaded assembly domain.

Is there a way to download CSLA debug sources (.pdb) as for `System` assemblies?

![image](https://user-images.githubusercontent.com/15612158/107980709-67789f00-6fc9-11eb-8eac-5548e91b1e28.png)

Cause without full debugable stack trace it's hard to decide something.

**Comment by rockfordlhotka** [comment]
The `MobileFormatter` follows the pattern set forth by `BinarySerializer`, which is to use `Type.GetType`.

The workaround I referred to is, in fact, to handle the appdomain event for failing to find a type, and to return the type by searching the list of types in the appdomain/process.

I don't plan to change `MobileFormatter` (or the rest of CSLA) to customize how types are found, because this is an extreme edge case (you are the first to try this since 2002), and there's a viable workaround.

**Comment by BaHXeLiSiHg** [comment]
Heh, was little bit busy.

Looks like the ```RunLocal``` is kind of extended property for ```MethodInfo``` class and used inside "user-defined" code.

What do you mean by "handle the appdomain event for failing"? To make some extension method for ```System.Type.GetType```?

**Comment by rockfordlhotka** [comment]
`RunLocal` is a custom attribute that can be applied to methods.

Regarding the appdomain event - there's an event you can handle off the appdomain that is raised when a type can't be found by normal `Type.GetType`. In that handler, you can find the type yourself and return it for use by the runtime.

[Here's a link](https://github.com/MarimerLLC/csla/blob/62de3c309e7ada00ebe29b8ad67a8de7d7f73904/cslacs10/NetRun/Launcher.cs#L49) to the code I'm talking about.

**Comment by BaHXeLiSiHg** [comment]
That make sense now, thanks.

Implemented such behavior, but got next error ```Resolving to a collectible assembly is not supported.```.

Every dynamic assembly, which is loaded inside separate ```AssemblyLoadContext```, is marked as collectible, in order to be collected by GC :\

That's my call stack now:
```
System.NotSupportedException: Resolving to a collectible assembly is not supported.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Csla.Reflection.MethodCaller.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Csla.Reflection.MethodCaller.GetType(String typeName)
   at Csla.Serialization.Mobile.MobileFormatter.GetTypeFromCache(String typeName)
   at Csla.Serialization.Mobile.MobileFormatter.DeserializeAsDTO(List`1 deserialized)
   at Csla.Serialization.Mobile.MobileFormatter.Deserialize(Stream serializationStream)
   at Csla.Core.ObjectCloner.Clone(Object obj)
   at Csla.Core.BusinessBase.GetClone()
```

Still investigating what is wrong and if it is possible to return collectible assembly by ```AppDomain.CurrentDomain.AssemblyResolve``` event handler.

**Comment by BaHXeLiSiHg** [comment]
Depends on resolver event, my returned assembly is kind of ```RuntimeAssembly (asm is RuntimeAssembly rtAssembly)```.

![image](https://user-images.githubusercontent.com/15612158/109815701-9bde9300-7c38-11eb-85d8-53de598a53cd.png)

But then exception was thrown within CSLA library:

![image](https://user-images.githubusercontent.com/15612158/109815310-2d013a00-7c38-11eb-982b-52d69a206105.png)

**Comment by rockfordlhotka** [comment]
Can you get the ToString value of that exception? That'll provide the full stack trace and other valuable information.

**Comment by BaHXeLiSiHg** [comment]
Same as provided before :(

**Comment by BaHXeLiSiHg** [comment]
I'm confused again, exception call stack shows that:

1) ```Resolving to a collectible assembly is not supported.``` - could accept this, cause assembly really is collectible, from collectible dynamic assembly domain, but i can't find any information about restrictions for manually handled (by ```AppDomain``` event after exception) assembly and seems like debugging of ```GetRuntimeAssembly``` method from system lib does not throw exception, means that manually provided assembly was accepted.
2) ```System.IO.FileLoadException: Could not load file or assembly``` - don't understand which code part is trying to load assembly, assembly was provided manually via event resolver.
3) Call stack on second screenshot shows that i handled exception from ```Csla.Reflection```, is there any checks if assembly exists in current application ```AppDomain```??

Not sure where i should digging :\

**Comment by rockfordlhotka** [comment]
I'd recommend taking CSLA out of the equation. The `Csla.Reflection` namespace is mostly wrappers around various .NET reflection code, necessary to handle differences in Silverlight and WinRT from "normal" .NET.

That's why the stack trace is valuable - you can follow it down through higher levels to find the original exception at the bottom of the stack, which is `System.IO.FileLoadException`.

**Comment by BaHXeLiSiHg** [comment]
Still fighting with ```ContextualReflectionScope``` of ```AssemblyLoadContext```. It should isolate types and static properties and hope will handle the ```Load``` exception from simple ```Type.GetType``` method in case of dynamically loaded assemblies.

I'm discussing this here [https://github.com/dotnet/runtime/issues/49132](url)

In short:
1) ```AppDomain``` seems like obsolete and used just for historical compatibility, recommendation is to use default ```AssemblyLoadContext.Default```.
2) ```AppDomain``` could not return collectible assembly from ```AssemblyResolveEventHandler```.
3) Simple ```GetType``` could be deprecated too in preference of his extensions, with possibility of providing ```assemblyResolver```.

Currently i have resolved (i hope so) memory leaks after loading/unloading of dynamic assemblies (glad to ```ContextualReflectionScope```) but still facing same assembly ```Load``` exception when trying to create/copy business object.

**Comment by BaHXeLiSiHg** [comment]
Seems like done with vanilla ```System.Type.GetType``` within dynamically loaded assembly. Hope that only caching issue remains :)

**Comment by BaHXeLiSiHg** [comment]
@rockfordlhotka, tell me please, where should i make changes)) at ```Csla.NetStandard2.0```?

**Comment by BaHXeLiSiHg** [comment]
Nvm, updated my project from ```netcore3.1``` to ```aspnet5.0```.

Will try to use partial flushing concept, started with file where i have encountered exception ```ServiceProviderMethodCaller```.

```diff
 using System.Threading.Tasks;

+#if NET5_0_OR_GREATER
+using System.Runtime.Loader;
+#endif

 using Csla.Properties;
```
```diff
+#if NET5_0_OR_GREATER
+    private static readonly ConcurrentDictionary<string, Tuple<string, ServiceProviderMethodInfo>> _methodCache =
+          new ConcurrentDictionary<string, Tuple<string, ServiceProviderMethodInfo>>();
+#else
+    private static readonly ConcurrentDictionary<string, ServiceProviderMethodInfo> _methodCache =
+      new ConcurrentDictionary<string, ServiceProviderMethodInfo>();
+#endif
```
```diff
       var cacheKey = GetCacheKeyName(targetType, typeOfOperation, criteria);
+
+#if NET5_0_OR_GREATER
+      if (_methodCache.TryGetValue(cacheKey, out var unloadableCachedMethodInfo))
+      {
+        var cachedMethod = unloadableCachedMethodInfo.Item2;
+
+        if (!throwOnError || cachedMethod != null)
+          return cachedMethod;
+      }
+#else
+      if (_methodCache.TryGetValue(cacheKey, out ServiceProviderMethodInfo cachedMethod))
+        if (!throwOnError || cachedMethod != null)
+            return cachedMethod;
+#endif
```
```diff
               else
+              {
+#if NET5_0_OR_GREATER
+                _methodCache.TryAdd(cacheKey, null);
+#else
+                _methodCache.TryAdd(cacheKey, null);
+#endif
+
+                return null;
+              }
```
```diff
       }

+#if NET5_0_OR_GREATER
+      var assemblyLoadContextName = AssemblyLoadContext.CurrentContextualReflectionContext?.Name;
+
+      if (!string.IsNullOrWhiteSpace(assemblyLoadContextName) && assemblyLoadContextName != AssemblyLoadContext.Default.Name)
+      {
+        AssemblyLoadContext.CurrentContextualReflectionContext.Unloading += OnAssemblyLoadContextUnload;
+      }
+
+      _methodCache.TryAdd(cacheKey, new Tuple<string, ServiceProviderMethodInfo>(assemblyLoadContextName, resultingMethod));
+#else
+      _methodCache.TryAdd(cacheKey, resultingMethod);
+#endif

       return resultingMethod;
```
```diff
+#if NET5_0_OR_GREATER
+    private static void OnAssemblyLoadContextUnload(AssemblyLoadContext context)
+    {
+      if (context == null)
+      {
+        return;
+      }
+
+      var obsoleteCacheKeys = new List<string>();
+
+      foreach (var (cacheKey, unloadableMethodInfo) in _methodCache)
+      {
+        if (unloadableMethodInfo == null)
+        {
+          continue;
+        }
+
+        if (unloadableMethodInfo.Item1 == context.Name)
+        {
+          obsoleteCacheKeys.Add(cacheKey);
+        }
+      }
+
+      foreach (var obsoleteCacheKey in obsoleteCacheKeys)
+      {
+        _ = _methodCache.TryRemove(obsoleteCacheKey, out _);
+      }
+    }
+#endif
```

After those changes exception is gone. If changes above is fine, i'm going to analyze and improve other "caching" parts, cause right now ```GCDumps``` showing me lot of leaks of ```CSLA``` properties and my libraries after ```Loading -> Unloading -> Dump -> Loading -> Unloading -> Dump``` process.

**Comment by rockfordlhotka** [comment]
In the main branch there is now just one `Csla` project with all the code.

In the v5.x branch all the core code is in the `Csla.Shared` project.

**Comment by BaHXeLiSiHg** [comment]
Heh, encountered surprising behavior :\

Edited all places with caching and implemented partial cache flushing, depends on activated context ```AssemblyLoadContext.CurrentContextualReflectionContext``` at caching moment.

Problems came from common class ```FetchCriteria```, inherited from ```CriteriaBase```, it is inside common application part and are used by dynamically loaded assemblies. So, if it is common part it should exist (register all static information) in default context - ```AssemblyLoadCotnext.Default```, but first activation of instance ```FetchCriteria``` happens within dynamically loaded assembly, that means inside active ```ContextualReflectionScope``` of this dynamic assembly and it means that all static parts of ```FetchCriteria``` should be stored inside dynamic context and unloaded with it.

The problem is that method ```internal static PropertyInfo<T> RegisterProperty<T>(Type objectType, PropertyInfo<T> info)``` from ```PropertyInfoManager.cs``` fires only on first activation of class ```FetchCriteria```. But when class ```FetchCriteria``` was activated inside active ```ContextualReflectionScope```, according to logic provided in my previous post, cached information in ```PropertyInfoManager.cs``` will be erased after assembly unloads.

After dynamic assembly reloading and activating, ```FetchCriteria``` class adding itself to cache again but does not register his properties second time, using ```RegisterProperty``` method. Seems like static information about ```FetchCriteria``` class properties was stored somewhere?

Every other classes, created inside dynamic assemblies, successfully recalling ```RegisterProperty``` method every time, after unload/load process.

Will be grateful for any ideas!

**Comment by BaHXeLiSiHg** [comment]
Never mind, figured out how to handle this. Little bit strange, but no memory leaks from CSLA side.

![image](https://user-images.githubusercontent.com/15612158/112035151-f12b0780-8b47-11eb-8538-df339042d2d4.png)

**Comment by BaHXeLiSiHg** [comment]
@rockfordlhotka, am i free to push fork of v5.x branch or there are some restrictions? Cause i'm not able, getting 403 (login) error and not sure if it is from my side, or not.

**Comment by rockfordlhotka** [comment]
Changes are managed through pull request (PR), so they can be reviewed by folks, and so the CI build process is triggered.

You can read through these instructions, which you might need to adapt a little depending on how you set up your working branch within your fork.

https://github.com/MarimerLLC/csla/blob/main/docs/dev/csla-github-flow.md

**Comment by ProDInfo** [comment]
I have the same problem with one of my projects that load assembly and give the same error:

```Can` not cast [A]MyClass from MyAssembly.dll to [B]MyClass from MyAssembly.dll```

I solve with change loading assembly from:

```Assembly.Load(...)```

to

```Assembly.LoadFrom(...)```

Probably help us on this issue

**Comment by BaHXeLiSiHg** [comment]
@rockfordlhotka hey, do we have separate branch for version 6.x or i should modify ```main``` branch?

**Comment by rockfordlhotka** [comment]
@BaHXeLiSiHg `main` is the v6 branch, so please do the PR to `main`.

**Comment by BaHXeLiSiHg** [comment]
@rockfordlhotka, does the ```Dynamic Constructor Cache``` region of ```MethodCaller.cs``` is obsolete? Because there is no references to this method and also i didn't add "re-cashing" logic for it, in version ```5.x``` :\
