### ISSUE TITLE
'Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, '

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#2398]
**Describe the bug**
Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

**Version and Platform**
CSLA version: CSLA 5.5.0
OS: Windows
Platform: UWP etc.

**Code that Fails**

```c#
var list = await ProjectTracker.Library.ProjectList.GetProjectListAsync();
```

**Stack Trace or Exception Detail**

```text
   at Csla.DataPortalClient.HttpProxy.<Fetch>d__28.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.DataPortal`1.<DoFetchAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.DataPortal`1.<FetchAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.DataPortal.<FetchAsync>d__28`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ProjectTracker.Library.ProjectList.<GetProjectListAsync>d__1.MoveNext() in E:\Uno\csla-main\csla-main\Samples\ProjectTracker\ProjectTracker.BusinessLibrary.Netstandard\ProjectList.cs:line 34
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UwpUI.MainPage.<Page_Loaded>d__6.MoveNext() in E:\Uno\csla-main\csla-main\Samples\ProjectTracker\ProjectTracker.Ui.UWP\MainPage.xaml.cs:line 41
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

**Additional context**
getting above exception after upgrading csla to 5.5.0 version

**Comment by rockfordlhotka** [comment]
I suspect this is related to changes made in #2095. @BaHXeLiSiHg may be able to provide some insight.

**Comment by rockfordlhotka** [comment]
Whatever resolution occurs for v5.5.0 needs to be incorporated into the changes made for CSLA 6 in #2095

**Comment by rockfordlhotka** [comment]
@SachinPNikam I'm looking through the code and I wonder if you can just add a reference to the `System.Runtime.Loader` nuget package to your project to resolve the issue?

We might be missing that dependency in the `Csla` package definition.

**Comment by rockfordlhotka** [comment]
Actually it appears that part of the assembly loader functionality snuck into the netstandard2.0 codebase, rather than being restricted to .NET 5.0 and higher as intended.

@SachinPNikam I _suspect_ that if you add that nuget package it'll be a workaround, but I've changed the code for v5.5.1 so it won't be necessary.

**Comment by rockfordlhotka** [comment]
Nope, I am wrong - the change was due to #2229, and the bug is that the nuspec for the `Csla` package is just missing the package dependency for `System.Runtime.Loader` - so no code changes required, just a fix to the nuspec.

**Comment by SachinPNikam** [comment]
> 
> 
> @SachinPNikam I'm looking through the code and I wonder if you can just add a reference to the `System.Runtime.Loader` nuget package to your project to resolve the issue?
> 
> We might be missing that dependency in the `Csla` package definition.

I tested with adding System.Runtime.Loader` nuget into project -but it did not worked

**Comment by rockfordlhotka** [comment]
Did you add the 4.0.0 or 4.3.0 version? I think the exception said it wanted the older one?

**Comment by GreatBarrier86** [comment]
Is this fixed for sure? To make sure i had all the required dependencies, i uninstalled all CSLA related packages an reinstalled them from scratch. System.Runtime.Loader wasn't installed. Should it have been?

**Comment by GreatBarrier86** [comment]
Has this fixed been tested on Xamarin.Android? I'm running into a problem. Xamarin.Android doesn't support binding redirects and CSLA 5.5.2 requires version >= 4.3, but the error message is referencing version 4.0. I tried installing 4.0 within the Xamarin project but the Nuget UI won't allow it.

**Comment by rockfordlhotka** [comment]
Can you create this as a new issue please?
