### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.    at System.Collections.Generic.List`1.Add(T item)    at Csla382.Security.AuthorizationRules.DenyRead(String propertyName, String[] roles) in c:\Source\Dev\Common\CSLA.3.8.2\cslacs\Csla\Security\AuthorizationRules.cs:line 255

### ISSUE THREAD

**Issue by tomrb** [MarimerLLC/csla#2425]
When making a WCF REST Web Service call in our QA environment we are getting the following exception. We cannot replicate this bug in our DEV environment.

Timestamp:2021-08-11 03:48:59.0457 
Message: Csla382.DataPortalException: DataPortal.Fetch failed (Index was outside the bounds of the array.) ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at Csla382.Security.AuthorizationRules.DenyRead(String propertyName, String[] roles) in c:\Source\Dev\Common\CSLA.3.8.2\cslacs\Csla\Security\AuthorizationRules.cs:line 255
   at Abbott.ADD.CMSNext.Library.Contact.AddInstanceAuthorizationRules() in e:\_work\40\s\Common\CMSNextLibrary\Contact.cs:line 591
   at Csla382.Core.BusinessBase.InitializeAuthorizationRules() in c:\Source\Dev\Common\CSLA.3.8.2\cslacs\Csla\Core\BusinessBase.cs:line 392
   at Csla382.Core.BusinessBase..ctor() in c:\Source\Dev\Common\CSLA.3.8.2\cslacs\Csla\Core\BusinessBase.cs:line 49
   at Csla382.BusinessBase`1..ctor()
   at ctor()
   at Csla382.Reflection.MethodCaller.CreateInstance(Type objectType) in c:\Source\Dev\Common\CSLA.3.8.2\cslacs\Csla\Reflection\MethodCaller.cs:line 147
   at Csla382.Reflection.LateBoundObject..ctor(Type objectType) in c:\Source\Dev\Common\CSLA.3.8.2\cslacs\Csla\Reflection\LateBoundObject.cs:line 29
   at Csla382.Server.SimpleDataPortal.Fetch(Type objectType, Object criteria, DataPortalContext context) in c:\Source\Dev\Common\CSLA.3.8.2\cslacs\Csla\Server\SimpleDataPortal.cs:line 106
   --- End of inner exception stack trace ---
   at Csla382.DataPortal.Fetch(Type objectType, Object criteria) in c:\Source\Dev\Common\CSLA.3.8.2\cslacs\Csla\DataPortal.cs:line 262
   at Csla382.DataPortal.Fetch[T](Object criteria) in c:\Source\Dev\Common\CSLA.3.8.2\cslacs\Csla\DataPortal.cs:line 173
   at CMSNext.Mobile.Repository.ContactFactoryV2.UpdateContact(ContactUpdate contactUpdateModel) in e:\_work\40\s\Integrations\WebService\CMSNext.Mobile.Repository\ContactFactoryV2.cs:line 121
   at CMSNext.Mobile.Wcf.ContactServiceV2.UpdateContact(ContactUpdate contactUpdateModel) in e:\_work\40\s\Integrations\WebService\CMSNext.Mobile.Wcf\ContactServiceV2.cs:line 116

**Comment by rockfordlhotka** [comment]
This sounds like one of a couple things.

First, _maybe_ it could be that the production server hasn't been configured to allow IIS, ASP.NET, and WCF to support max upload/download data sizes. This is discussed in the _Using CSLA 4_ book.

Second, and probably more likely, it sounds like the server is returning some HTML instead of the expected byte stream. This happens usually because of a security issue. The easiest way to see what's happening is if you can put fiddler on the connection to see what is coming back from the server.
