### ISSUE TITLE
Error in ProjectTracker sample: 'Object is still being edited and can not be saved'

### ISSUE THREAD

**Issue by bujma** [MarimerLLC/csla#2814]
**Steps:**
- no configuration or code change after downloading the sources
- ProjectTracker.Ui.WPF and ProjectTracker.AppServerCore as startup projects
- run, login as 'manager'
- go to Project List
- press [Edit] on any project
- change some editable field
- press [Save]
- => Object is still being edited and can not be saved

**Version and Platform**
CSLA version: 5.5.1 as referenced in downloaded sources of v5.x branch (tried also with 5.5.2)
OS: Windows
Platform: WPF

**Code that Fails**
https://github.com/MarimerLLC/csla/blob/dfaf1520e0e5acc05ee910b4f88703aafa137822/Samples/ProjectTracker/ProjectTracker.Ui.WPF/ViewModels/ViewModelLocalEdit.cs#L22

**Stack Trace**
```
   at Csla.BusinessBase`1.<SaveAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.BusinessBase`1.<SaveAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.BusinessBase`1.<SaveAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.BusinessBase`1.<Csla-Core-ISavable-SaveAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Xaml.ViewModelBase`1.<SaveAsync>d__92.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WpfUI.ViewModels.ViewModelLocalEdit`1.<Save>d__1.MoveNext() in C:\Work\Csla\csla-5.x\Samples\ProjectTracker\ProjectTracker.Ui.WPF\ViewModels\ViewModelLocalEdit.cs:line 22
```

**Comment by bujma** [comment]
Sorry, if off-topic for this issue: where can I get some reference to sources of working WPF example applications as complex as ProjectTracker (PT) is (or more) until PT WPF is fixed? (I assume CSLA .NET 5.5.2 is working, just PT WPF is not.) We would like to try CSLA .NET and explore the concepts in some working examples but currently we are not able to find any that's working. Thanks much.

**Comment by rockfordlhotka** [comment]
@bujma please post that last question in the Discussion tab.

**Comment by rockfordlhotka** [comment]
#2551
