### ISSUE TITLE
NullReferenceException when type is missing a suitable constructor

### ISSUE THREAD

**Issue by ajk108** [MarimerLLC/csla#307]
This is in 4.5.601.0.

I apparently wasn't paying attention and didn't define a parameterless constructor for one of my business objects, but this was the exception that the client received when DataPortal.Fetch was called:

```
  DataPortal.Fetch failed (Object reference not set to an instance of an object.)
   at Csla.Server.SimpleDataPortal.<Fetch>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Csla.Server.DataPortalSelector.<Fetch>d__5.MoveNext()
   at Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   at Csla.DataPortal`1.Fetch(Object criteria)
   at Csla.DataPortal.Fetch[T](Object criteria)
   at Harld.Data.Entities.Keys.RoomKeyCollection.Search(KeySearchCriteria criteria)
[snip]
```

I traced this back to the `finally` block at line 177 of SimpleDataPortal.cs:
```
finally
{
   ApplicationContext.DataPortalActivator.FinalizeInstance(obj.Instance);
}
```

obj is initialized as null, but if the activator fails to find a suitable constructor, then its resulting NotImplementedException is silently ignored. So, when we reach the block, obj is still null.

**Comment by rockfordlhotka** [comment]
Might be related to #249
