### ISSUE TITLE
Serialize failure after update to 5.5.3

### ISSUE THREAD

**Issue by HeSitates** [MarimerLLC/csla#3270]
**Describe the bug**
We are updating (finally 😢) from .Net Framework 4.7 to 4.8 and from CSLA v4.3.14 to v5.5.3. Besides adding some attributes (Create and Execute), almost no other change. 

But still I get an excption when saving a quite big object to the database. See Stack Trace below.

The object mentioned in the stacktrace (IncompleteDateTime) we use a lot in our code and has never been a problem. And added an extra unittest for it to test the serializabillity and that succeedd as well.

Even build an integration test with the same message and all the steps that are done in the MessageProcessor. But whereas the MessageProcessor fails, the integration test can save the object to the database.

Does anyone have a  hint for me why this exception is thrown after this update? And not in the old framework/CSLA and in the same code in the integration test?

**Version and Platform**
CSLA version: 5.5.3
OS: Windows
Platform: Windows service (.Net Framework 4.8)

**Code that Fails**
The object from the stack trace:
```csharp
  using System;

  [Serializable]
  public class IncompleteDateTime : IComparable, IComparable<IncompleteDateTime>
  {
    public IncompleteDateTime()
    {
    }

    public IncompleteDateTime(DateTime? value)
    {
      Value = value;
    }

    public IncompleteDateTime(DateTime? value, string incompleteness)
    {
      Value = value;
      Incompleteness = incompleteness;
    }

    public DateTime? Value { get; set; }

    public string Incompleteness { get; set; }
}
```

**Stack Trace or Exception Detail**
```
System.NotSupportedException
  HResult=0x80131515
  Message=Serialization of type object is not supported. (BLL.IncompleteDateTime)
  Source=Csla
  StackTrace:
   at Csla.BusinessBase`1.Save()
   at Processors.CSLAOracleStufProcessor`4.ProcessToevoeging(DtoKennisgevingsBericht kennisgeving) in D:\Agents\Agent.Morpheus\_work\12\s\Stuf Components\Processors\CSLAOracleStufProcessor.cs:line 175
   at Processors.CSLAOracleStufProcessor`4.ProcessKennisgeving(DtoKennisgevingsBericht kennisgeving) in D:\Agents\Agent.Morpheus\_work\12\s\Stuf Components\Processors\CSLAOracleStufProcessor.cs:line 67
   at MessageProcessor.Service.Stuf0310.MessageProcessorStuf0310.ProcessMessage(DtoKennisgevingsBericht dto) in **************MessageProcessor.Service\Stuf0310\MessageProcessorStuf0310.cs:line 96
   at MessageProcessor.Service.Stuf0310.MessageProcessorStuf0310.ProcessMessageContent(Object content) in **************MessageProcessor.Service\Stuf0310\MessageProcessorStuf0310.cs:line 78
   at MessageProcessor.Service.MessageProcessor.ProcessMessage(Message message) in **************MessageProcessor.Service\MessageProcessor.cs:line 273

  This exception was originally thrown at this call stack:
    Csla.BusinessBase<T>.Save()
    Processors.CSLAOracleStufProcessor<S, BO, TA, DO>.ProcessToevoeging(Base.DtoKennisgevingsBericht) in CSLAOracleStufProcessor.cs
    Processors.CSLAOracleStufProcessor<S, BO, TA, DO>.ProcessKennisgeving(Base.DtoKennisgevingsBericht) in CSLAOracleStufProcessor.cs
    MessageProcessor.Service.Stuf0310.MessageProcessorStuf0310.ProcessMessage(Base.DtoKennisgevingsBericht) in MessageProcessorStuf0310.cs
    MessageProcessor.Service.Stuf0310.MessageProcessorStuf0310.ProcessMessageContent(object) in MessageProcessorStuf0310.cs
    MessageProcessor.Service.MessageProcessor.ProcessMessage(Bus.Message) in MessageProcessor.cs
```
**Additional context**

**Comment by JacoJordaan** [comment]
My guess is that you need to look into the nullable DateTime field. It may be that the serialization has changed to MobileFormatter from BinaryFormatter. MobileFormatter will only be able to format primitive types. It may be that a nullable type is seen as an object and not as a DateTime.

**Comment by HeSitates** [comment]
Thanks!

I had to add the `IMobileObject` interface to the class:
```csharp
    public void GetState(SerializationInfo info)
    {
      if (Value.HasValue)
      {
        info.AddValue(nameof(Value), Value.Value);
      }

      if (Incompleteness != null)
      {
        info.AddValue(nameof(Incompleteness), Incompleteness);
      }
    }

    public void GetChildren(SerializationInfo info, MobileFormatter formatter)
    {
      // Intentionally left empty
    }

    public void SetState(SerializationInfo info)
    {
      if (info.Values.ContainsKey(nameof(Value)))
      {
        this.Value = (DateTime)info.Values[nameof(Value)].Value;
      }

      if (info.Values.ContainsKey(nameof(Incompleteness)))
      {
        Incompleteness = info.Values[nameof(Incompleteness)].Value?.ToString();
      }
    }

    public void SetChildren(SerializationInfo info, MobileFormatter formatter)
    {
      // Intentionally left empty
    }
```
Now I have only one question left: In all of our other projects (which where converted earlier) we've used this class without the interface. Why didn't we run into problems there? 🤔
