### ISSUE TITLE
new BlazorExample error

### ISSUE THREAD

**Issue by uwefms** [MarimerLLC/csla#3654]
Hi,
 
   when trying to explore the new .net8 BlazorExample I get the following error when trying to add a person:

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Authorization requires a cascading parameter of type Task<AuthenticationState>. Consider using CascadingAuthenticationState to supply this.
System.InvalidOperationException: Authorization requires a cascading parameter of type Task<AuthenticationState>. Consider using CascadingAuthenticationState to supply this.
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

  regards
   
     Uwe

**Comment by rockfordlhotka** [comment]
Yes, I'm still trying to resolve that issue - learning more details about authentication/authorization in Blazor 8.

**Comment by ctwoodwa** [comment]
I finally have some time to get back to learning CSLA.  When I open the latest Blazor sample project the version is 8.0.0-R24010204, but this version is not listed on Nuget.  the latest version is 8.0.0-R24010305, but if I use this version there are a couple of compile issues.  Any recommendations on how to proceed?

**Comment by rockfordlhotka** [comment]
@ctwoodwa I was able to update to the R24010305 release and have the app work (with the exception of the wasm page as noted above). There were some compile warnings, but they went away on a subsequent rebuild, so I think it was due to old stuff in the obj folders.
