### ISSUE TITLE
CslaValidation component needs to implement IValidationMessageStore

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#3918]
In a Blazor `EditForm` you can use the `CslaValidator` and `CslaValidationMessages` components like this:

```html
    <EditForm Model="@Person" OnSubmit="Save">
        <CslaValidator />
        <ValidationSummary />

        <InputText @bind-Value="Person.Name" />
        <CslaValidationMessages For="() => Person.Name" />
        <button type="submit">Save</button>
    </EditForm>
```

This _should_ cause validation messages to appear when the user tabs out of the `InputText` control with a broken rule, 

It doesn't work properly right now, because `CslaValidator` doesn't implement the `IValidationMessageStore` interface (at least according to Copilot).

**Comment by Freelancingonupwork** [comment]
Hello, you mean custom IValidationMessageStore interface?

**Comment by rockfordlhotka** [comment]
> Hello, you mean custom IValidationMessageStore interface?

I am not 100% sure.

Right now, if you implement an EditForm over a type that uses DataAnnotations attributes and use the standard data annotations validator in the EditForm, you can see how the form works at runtime.

If you implement an EditForm over a type that uses CSLA business rules that do the same thing (like the `Required` rule), and use the CSLA validator in the EditForm, you can see how _that_ form works at runtime.

The two don't work quite the same in terms of when the broken rule results appear to the user.

My _guess_ is that something is missing in the `CslaValidator` implementation to get the same behavior - and my thought is that the behavior should be the same (or as close as possible).

**Comment by kant2002** [comment]
I did try to place `EditPerson.razor` and seems to be everything working as expected. Please clarify if that's not the case.
```
<EditForm Model="@vm.Model" OnSubmit="vm.SaveAsync">
    <CslaValidator />
    <ValidationSummary />

    <InputText @bind-Value="vm.Model.Name" />
    <CslaValidationMessages For="() => vm.Model.Name" />
    <button type="submit" disabled="@(!vm.Model.IsSavable)">Save</button>
</EditForm>
```

Steps
1. Open Edit person for Andy,
2. Edit  Andy to andy
3. Press tab, and I see the `Check capitalization` which is clearly CSLA validation

![image](https://github.com/MarimerLLC/csla/assets/4257079/b1e065b0-7c14-4c8e-b7c8-5dfbee365c7c)

If I do slightly different steps,
1. Open Edit person for Andy,
2. Edit  Andy to empty string
3. Press tab, and I see the `The Name field is required.` which is clearly not CSLA validation

![image](https://github.com/MarimerLLC/csla/assets/4257079/13eef17e-e47d-4ad7-8373-d0e4ea2c26c2)

can you give more details what's wrong?

**Comment by rockfordlhotka** [comment]
@kant2002 I think that both behaviors are from CSLA, because the only validation component in the page is the `CslaValidator`. 

If you create a different page that uses data annotations validation against a simple object with a name property like this:

```c#
[Required]
public string Name { get; set; }
```

You'll see similar, but not the same, behavior.

The point of this issue is that there's something wrong with the `CslaValidator`, because it should match the behavior of the data annotations validator, at least for _error severity_ rules.

**Comment by kant2002** [comment]
Here probably my limited knowledge about CSLA, but I take Razor snipped from original post. and add following code.

```csharp
public PersonModel Person { get; set; } = new();

public void Save()
{

}

public class PersonModel
{
    [Required]
    public string Name { get; set; }
}
```

When I run the application and type anything in the text box, it will immidiately produce `NullReferenceException`. It seems that `CslaValidator` expect the model to be derived from `ICheckRules`. Is this expected? If so, probably it would be great to change error message to something more actionable then `System.ArgumentException: 'Model'` ?

**Comment by kcabral817** [comment]
Kant, you cannot initialize a CSLA object with new.  Here is the way to do that:  var obj = 

private readonly ApplicationContext _app;

_app.CreateInstanceDI<CSLA-BUSINESS-CLASS-NAME>();

**Comment by kant2002** [comment]
@kcabral817 does not helps. Same issue as before.

```razor
@inject ApplicationContext _app
....
protected override async Task OnInitializedAsync()
{
    // Every page _must_ initialize the state manager
    await StateManager.InitializeAsync();
    Person = _app.CreateInstanceDI<PersonModel>();
}
```

Location of error.

https://github.com/MarimerLLC/csla/blob/d31cff3c02d08baa8d27396d6bb71871831437c8/Source/Csla.Blazor/CslaValidationMessages.razor.cs#L210-L214

**Comment by kant2002** [comment]
`_fieldIdentifier.Model` is of type `PersonModel` which is barebone C# class. Maybe I misinterpret what `simple object` means?

**Comment by rockfordlhotka** [comment]
I was not clear.

I am suggesting having two pages in the test app.

Page 1 uses CSLA and a CSLA business object with the `CslaValidator`.

Page 2 uses a POCO with data annotations and the data annotations validator. No CSLA at all.

The goal is to have the behavior of the CSLA validator and the data annotations validator be as close as possible. Ideally they'd be the same behavior.

**Comment by kant2002** [comment]
I do not see any differences. Maybe you have other scenarios which I can check?
I test following classes:
- PersonEdit from original BlazorExample
- PerosnModel with 1 Name property with Required attribute and custom written NoZAllowedAttribute

Scenarios which I test in both CslaValidator and DataAnnotations validator.

1. Edit valid record Andy
2. No error messages initially.
3. Remove all text. Press Tab. Message "The Name field is required."
4. Type carl. All fine.

1. Edit in-valid record Buzz
2. No error messages initially.
3. Type 1 at the end of Buzz. Press Tab. Message "No letter Z allowed"
4. Remove all text. Press Tab. Message "The Name field is required."
5. Type carl. All fine.

------------
I also observe other annoying issues when I try load data via Data portal. That's with changes from #4043 applied.
```
rit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: SetUser
Csla.DataPortalException: SetUser

   at Csla.DataPortalClient.DataPortalProxy.Fetch(Type objectType, Object criteria, DataPortalContext context, Boolean isSync) in C:\d\github\csla\Source\Csla\DataPortalClient\DataPortalProxy.cs:line 171
   at Csla.DataPortal`1.<>c__DisplayClass24_1.<<DoFetchAsync>b__0>d[[BusinessLibrary.PersonEdit, BusinessLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\d\github\csla\Source\Csla\DataPortalT.cs:line 222
--- End of stack trace from previous location ---
   at Csla.DataPortalClient.DataPortalNoCache.GetDataPortalResultAsync(Type objectType, Object criteria, DataPortalOperations operation, Func`1 portal) in C:\d\github\csla\Source\Csla\DataPortalClient\DataPortalNoCache.cs:line 27
   at Csla.DataPortal`1.<DoFetchAsync>d__24[[BusinessLibrary.PersonEdit, BusinessLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\d\github\csla\Source\Csla\DataPortalT.cs:line 240
   at Csla.DataPortal`1.<FetchAsync>d__29[[BusinessLibrary.PersonEdit, BusinessLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\d\github\csla\Source\Csla\DataPortalT.cs:line 335
   at BlazorExample.Client.Components.Pages.EditPersonValidation.OnInitializedAsync() in C:\d\github\csla\Samples\BlazorExample\BlazorExample\BlazorExample.Client\Components\Pages\EditPersonValidation.razor:line 43
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
------------------------------
System.NotSupportedException: SetUser
   at Csla.AspNetCore.Blazor.ApplicationContextManagerBlazor.SetUser(IPrincipal principal) in C:\d\github\csla\Source\Csla.AspNetCore\Blazor\ApplicationContextManagerBlazor.cs:line 136
   at Csla.ApplicationContext.set_User(IPrincipal value) in C:\d\github\csla\Source\Csla\ApplicationContext.cs:line 66
   at Csla.Server.DataPortal.ClearContext(DataPortalContext context) in C:\d\github\csla\Source\Csla\Server\DataPortal.cs:line 733
   at Csla.Server.DataPortal.Fetch(Type objectType, Object criteria, DataPortalContext context, Boolean isSync) in C:\d\github\csla\Source\Csla\Server\DataPortal.cs:line 302
   at Csla.Server.Hosts.HttpPortal.Fetch(CriteriaRequest request) in C:\d\github\csla\Source\Csla.Web.Mvc.Shared\Server\Hosts\HttpPortal.cs:line 110
   at Csla.Server.Hosts.HttpPortalController.CallPortal(String operation, Object request) in C:\d\github\csla\Source\Csla.Web.Mvc.Shared\Server\Hosts\HttpPortalController.cs:line 284
   at Csla.Server.Hosts.HttpPortalController.InvokePortal(String operation, Stream requestStream, Stream responseStream) in C:\d\github\csla\Source\Csla.Web.Mvc.Shared\Server\Hosts\HttpPortalController.cs:line 199

```
