### ISSUE TITLE
Issue With Throwing an Exception and Getting MissingManifestResourceException

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#735]
I noticed in a test that it should be giving me a NotSupportedException, but my custom IDataPortalActivator's FinalizeInstance() is accidentally throwing a NullReferenceException. The problem, though, is that I end up getting this kind of exception:

Expected a <Csla.DataPortalException> to be thrown, but found a <System.Resources.MissingManifestResourceException>: System.Resources.MissingManifestResourceException with message "Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Csla.Properties.Resources.resources" was correctly embedded or linked into assembly "Csla" at compile time, or that all the satellite assemblies required are loadable and fully signed."
     at Csla.DataPortal`1.Create(Type objectType, Object criteria)
     at Csla.DataPortal`1.Create(Object criteria)
     at ...

I should note that the project is targeting .NET Standard 1.6, and I'm referencing 4.6.600

**Comment by JasonBock** [comment]
Actually, it doesn't matter what the exception is. Fixing the NullReferenceException issue still gives me the resource exception issue.
