### ISSUE TITLE
AmbiguousMatchException in FactoryDataPortal

### ISSUE THREAD

**Issue by iherwald** [MarimerLLC/csla#790]
This exception occures after updating from CSLA v4.6.500.0 to v4.6.603.0 when using the FactoryDataPortal and having two (Factory)DataPortal methods with the same name (but different signatures) in the same class.

```
        public PackageEdit Create(PackageEdit.CreateNewCriteria criteria)
        {
        }
        public PackageEdit Create(PackageEdit.CreateCopyCriteria criteria)
        {
        }
```
```
Stack Trace:
at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)\r\n
at System.Type.GetMethod(String name, BindingFlags bindingAttr)\r\n   
at Csla.Reflection.MethodCaller.GetMethod(Type objectType, String method, Boolean hasParameters, Object[] parameters)\r\n   
at Csla.Reflection.MethodCaller.GetCachedMethod(Object obj, String method, Boolean hasParameters, Object[] parameters)\r\n   
at Csla.Reflection.MethodCaller.IsAsyncMethod(Object obj, String method, Boolean hasParameters, Object[] parameters)\r\n   
at Csla.Utilities.ThrowIfAsyncMethodOnSyncClient(Boolean isSync, Object obj, String methodName)\r\n   
at Csla.Server.FactoryDataPortal.<InvokeMethod>d__5.MoveNext()\r\n
```
We moved back to v4.6.500.0 and the application works without any problems. 
I checked the new preview v4.7.100-Beta-17100905, but the exception still occures there.

**Comment by rockfordlhotka** [comment]
This is on full .NET 4.6? Or some different flavor/version?

**Comment by iherwald** [comment]
The (highest) installed .NET Framework is version 4.6.1.

The target framework for all application projects is version 4.5.2.

 

 

Von: Rockford Lhotka [mailto:notifications@github.com] 
Gesendet: Dienstag, 17. Oktober 2017 22:36
An: MarimerLLC/csla
Cc: iherwald; Author
Betreff: Re: [MarimerLLC/csla] AmbiguousMatchException in FactoryDataPortal (#790)

 

This is on full .NET 4.6? Or some different flavor/version?

**Comment by iherwald** [comment]
We can reproduce this behaviour in the current CSLA test project.

Test class: ObjectFactoryTests
1. add another create method to the class RootFactory (e.g. 'Create (int criteria)')
2. deactivate  method 'Create()' in class RootFactory
3. run test 'CreateLocal'

The AmbiguousMatchException will be thrown if method 'Create()' does not exist.

```
namespace Csla.Test.ObjectFactory
{
  public class RootFactory
  {
        //public object Create()
        //{
        //  var obj = new Root();
        //  obj.Data = "Create";
        //  obj.Location = ApplicationContext.ExecutionLocation;
        //  obj.MarkAsNew();
        //  return obj;
        //}

        // This overload method will not be called,
        // but AmbiguousMatchException will be thrown,
        // if method 'Create()' does not exist.
        public object Create(int criteria)
        {
            return new Root();
        }

	[RunLocal]
	public object Create(SingleCriteria<Root, string> criteria)
	{
	  var obj = new Root();
	  obj.Data = "Create " + criteria.Value;
	  obj.Location = ApplicationContext.ExecutionLocation;
	  obj.MarkAsNew();
	  return obj;
	}

     }
}
```

**Comment by KC7465128305** [comment]
I am on CSLA 5.4.1 and I got this AmbiguousMatchException error.  Here is the exception detail:

Csla.DataPortalException
  HResult=0x80131500
  Message=DataPortal.Create failed (BO.Systems.AppInfo.[Create](). Matches: BO.Systems.AppInfo[Void DataPortal_Create()], Csla.Core.BusinessBase[Void DataPortal_Create()])
  Source=Csla
  StackTrace:
   at Csla.Reflection.ServiceProviderMethodCaller.FindDataPortalMethod[T](Type targetType, Object[] criteria, Boolean throwOnError)
   at Csla.Server.DataPortal.Create(Type objectType, Object criteria, DataPortalContext context, Boolean isSync)
   at Csla.DataPortal`1.Create(Type objectType, Object criteria)
   at Csla.DataPortal`1.Create(Object[] criteria)
   at Csla.DataPortal.Create[T](Object[] criteria)
   at Csla.DataPortal.Create[T]()
   at BO.Systems.AppInfo.NewSystemInfo() in D:\Net5 Zurich2 VS 2019\SantaClara Mar 7, 21\XReport\BO\Systems\AppInfo.cs:line 122
   at BO.SharedClass.UtilClass.ResetDBAppAndDBData(String license64String) in D:\Net5 Zurich2 VS 2019\SantaClara Mar 7, 21\XReport\BO\SharedClass\CommonCodes.cs:line 1210
   at WPFUI.Dialogs.About.btnResetAll_Click(Object sender, RoutedEventArgs e) in D:\Net5 Zurich2 VS 2019\SantaClara Mar 7, 21\XReport\WPFUI\Dialogs\About.xaml.cs:line 40
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()

Inner Exception 1:
AmbiguousMatchException: BO.Systems.AppInfo.[Create](). Matches: BO.Systems.AppInfo[Void DataPortal_Create()], Csla.Core.BusinessBase[Void DataPortal_Create()]

**Comment by KC7465128305** [comment]
Ok, I downgraded CSLA from CSLA 5.4.1 back to CSLA 5.4.0 and the problem went away.  So it must be something in 5.4.1 that throws the AmbiguousMatchException
